version: 2
updates:
  - package-ecosystem: nix
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build(flake)
    groups:
      flake-inputs:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/nix-build
    schedule:
      interval: weekly
    commit-message:
      prefix: ci(cache)
    groups:
      actions:
        patterns: ["*"]
