services:
  devcontainer:
    image: nixos-config_devcontainer-devcontainer:latest
    build:
      context: .
      dockerfile: Dockerfile
    user: "0:0"
    privileged: true
    volumes:
      - ../../:/workspaces:cached
      - ./nix.conf:/etc/nix/nix.conf

      - nix-store:/nix

    hostname: devcontainer

    entrypoint: ["/nix/var/nix/profiles/default/bin/bash", "-lc"]

    environment:
      NIX_MULTI_USER: "true"
      NIX_REMOTE: "daemon"
      NIX_STATE_DIR: /nix/var/nix/workflow-state
      VSCODE_SERVER_CUSTOM_GLIBC_LINKER: "true"

    command:
      [
        "unset NIX_REMOTE; exec /nix/var/nix/profiles/default/bin/nix-daemon --store local",
      ]

volumes:
  nix-store:
    name: nixos-config_devcontainer_nix-store
