version: "3"
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ../../:/workspaces:cached
      - ./nix.conf:/etc/nix/nix.conf

      - nix-store:/nix

    hostname: devcontainer

    environment:
      NIX_MULTI_USER: "true"
      NIX_REMOTE: "daemon"
      VSCODE_SERVER_CUSTOM_GLIBC_LINKER: "true"

    command: sleep infinity

volumes:
  nix-store:
