filter-syscalls = false
experimental-features = nix-command flakes pipe-operators
extra-platforms = aarch64-linux
trusted-users = root vscode

# SUBSTITUTERS
extra-substituters = https://attic.xuyh0120.win/lantian https://cache.numtide.com https://chuccle.cachix.org https://nix-community.cachix.org
extra-trusted-public-keys = lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc= niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g= chuccle.cachix.org-1:FT8Le4No+sZMyaQEqyWAJdbikbo9CGRQxnFkB9Tl27w= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

# BUILD PARALLELISM
max-jobs = 1
cores = 2

keep-failed = false
