filter-syscalls = false
experimental-features = nix-command flakes pipe-operators
extra-platforms = aarch64-linux
trusted-users = root vscode

extra-substituters = https://chuccle.cachix.org https://nix-community.cachix.org
extra-trusted-public-keys = chuccle.cachix.org-1:FT8Le4No+sZMyaQEqyWAJdbikbo9CGRQxnFkB9Tl27w= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

max-jobs = 2
cores = 4

keep-failed = false
