;;;; Free-tier provider registration for Autolith.
;;;;
;;;; Generated by the autolith-lxc NixOS module. Loaded from
;;;; ${XDG_CONFIG_HOME}/autolith/init.lisp — "ordinary Common Lisp in package
;;;; AUTOLITH, with your full privileges" — after tracked code and before
;;;; provider requests, and again on every reconnect.
;;;;
;;;; IMPORTANT — read before assuming this behaves like ZeroClaw's ladder:
;;;; Autolith's provider layer (src/provider/registry.lisp,
;;;; src/provider/client.lisp) has no multi-provider fallback anywhere in it.
;;;; A role's request targets exactly one provider/model;
;;;; provider--call-with-bounded-retries only retries auth/transport errors
;;;; against *that same* provider, never a different one. There is nothing
;;;; here that automatically walks from a rate-limited vendor to the next —
;;;; ZeroClaw gets that from its own Rust `fallback` config field, Autolith
;;;; does not have an equivalent. `autolith-free-tier-ladder` below exists so
;;;; that fact is at least on hand rather than needing to be rediscovered:
;;;; the agent (or you, attached over ttyd) has to notice a vendor is
;;;; rate-limited and switch models itself.
;;;;
;;;; Groq and Cerebras aren't Autolith built-ins, so they're registered here
;;;; as OpenAI-compatible providers. Gemini, OpenRouter and Mistral are
;;;; built-in (`autolith auth gemini/openrouter/mistral`); OpenRouter and
;;;; Mistral read their key from OPENROUTER_API_KEY / MISTRAL_API_KEY
;;;; already, per Autolith's own env-var bootstrap, so they need nothing
;;;; from this file. Gemini's OAuth flow can't be scripted headlessly — run
;;;; `autolith auth gemini` once from an attached session.

(in-package :autolith)

(defun env-non-empty (name)
  "NIL for an unset or empty environment variable, its value otherwise."
  (let ((value (uiop:getenv name)))
    (and value (plusp (length value)) value)))

;; GROQ — usually the most generous free tier of the lot, so it's the rung
;; worth defaulting a role's :models to.
(let ((key (env-non-empty "GROQ_API_KEY")))
  (when key
    (register-openai-compatible-provider
     :name "groq"
     :description "Groq (free tier)"
     :endpoint "https://api.groq.com/openai/v1/chat/completions"
     :models-endpoint "https://api.groq.com/openai/v1/models"
     :headers (list (cons "Authorization" (format nil "Bearer ~A" key))))))

;; CEREBRAS
(let ((key (env-non-empty "CEREBRAS_API_KEY")))
  (when key
    (register-openai-compatible-provider
     :name "cerebras"
     :description "Cerebras (free tier)"
     :endpoint "https://api.cerebras.ai/v1/chat/completions"
     :models-endpoint "https://api.cerebras.ai/v1/models"
     :headers (list (cons "Authorization" (format nil "Bearer ~A" key))))))

(defun autolith-free-tier-ladder ()
  "Best-first list of \"provider/model\" identifiers this box currently has
credentials for. Only entries whose provider is actually registered/keyed
are included — Gemini is listed unconditionally since it authenticates via
a one-time interactive OAuth flow rather than an environment variable, so
its presence here can't be checked from an env var the way the others can.

No entry in this list is tried automatically on your behalf (see the file
header). Treat it as the manual escalation path: when the active model
starts erroring or rate-limiting, pick the next entry and switch to it."
  (remove-if
   #'null
   (list
    (and (env-non-empty "GROQ_API_KEY") "groq/llama-3.3-70b-versatile")
    (and (env-non-empty "GROQ_API_KEY") "groq/llama-3.1-8b-instant")
    (and (env-non-empty "CEREBRAS_API_KEY") "cerebras/llama-3.3-70b")
    (and (env-non-empty "CEREBRAS_API_KEY") "cerebras/llama3.1-8b")
    "gemini/gemini-2.5-flash"
    "gemini/gemini-2.5-flash-lite"
    (and (env-non-empty "OPENROUTER_API_KEY") "openrouter/deepseek/deepseek-chat-v3-0324:free")
    (and (env-non-empty "OPENROUTER_API_KEY") "openrouter/meta-llama/llama-3.3-70b-instruct:free")
    (and (env-non-empty "MISTRAL_API_KEY") "mistral/mistral-small-latest"))))
